/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => EditorWidthSlider
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/settings/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  sliderPercentage: "20",
  sliderPercentageDefault: "20",
  sliderWidth: "150"
};
var EditorWidthSliderSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app2, plugin) {
    super(app2, plugin);
    this.plugin = plugin;
  }
  // this.settings.sliderWidth
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("滑块宽度").setDesc("底部状态栏的宽度设置滑块宽度?").addText((text) => text.setPlaceholder("Slider width in px").setValue(this.plugin.settings.sliderWidth).onChange(async (value) => {
      this.plugin.settings.sliderWidth = value;
      this.plugin.updateSliderStyle();
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("滑块默认百分比").setDesc("您希望滑块的默认百分比是多少?").addText((text) => text.setPlaceholder("Slider width in px").setValue(this.plugin.settings.sliderPercentageDefault).onChange(async (value) => {
      this.plugin.settings.sliderPercentageDefault = value;
      this.plugin.updateSliderStyle();
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("注意:").setDesc(`为了自定义特定笔记的编辑器宽度，需要在该笔记的 YAML 属性区域中添加“editor-width”字段，例如“editor-width: 40”。除非您在每篇笔记的YAML属性中都进行设置，否则此设置不会全局应用于所有笔记。（注意：当笔记的YAML属性中设置了editor-width属性字段后，优先使用属性设置的栏宽值，而底部状态栏的滑块将不再作用作用于该笔记`);
  }
};

// src/modal/warning.ts
var import_obsidian2 = require("obsidian");
var WarningModal = class extends import_obsidian2.Modal {
  constructor(app2) {
    super(app2);
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.setText("编辑器的栏宽值必须是 0～100的整数值!");
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/main.ts
var EditorWidthSlider = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.pattern = /^(?:[0-9]{1,2}|100)$/;
  }
  // most important function, this gets executed everytime the plugin is first 
  // loaded, e.g. when obsidian starts, or when the user just installed the 
  // plugin
  async onload() {
    await this.loadSettings();
    this.addStyle();
    this.registerEvent(
      this.app.workspace.on("file-open", () => {
        this.updateEditorStyleYAML();
      })
    );
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => {
        this.updateEditorStyleYAML();
      })
    );
    this.registerEvent(
      this.app.metadataCache.on("changed", (file) => {
        const activeFile = this.app.workspace.getActiveFile();
        if (activeFile && file.path === activeFile.path) {
          this.updateEditorStyleYAML();
        }
      })
    );
    this.createSlider();
    this.addSettingTab(new EditorWidthSliderSettingTab(this.app, this));
    this.updateEditorStyleYAML();
  }
  // async onLoadFile(file: TFile) {
  // }
  onunload() {
    this.cleanUpResources();
  }
  // ---------------------------- SLIDER -------------------------------------
  createSlider() {
    const slider = document.createElement("input");
    slider.classList.add("editor-width-slider");
    slider.id = "editor-width-slider";
    slider.type = "range";
    slider.min = "0";
    slider.max = "100";
    slider.value = this.settings.sliderPercentage;
    slider.style.width = this.settings.sliderWidth + "px";
    slider.addEventListener("input", (event) => {
      if (this.noteWidthLocked) {
        this.showLockedNotice();
        return;
      }
      const value = parseInt(slider.value);
      this.settings.sliderPercentage = value.toString();
      this.saveSettings();
      this.updateEditorStyleYAML();
      sliderValueText.textContent = value.toString();
    });
    const sliderValueText = document.createElement("span");
    sliderValueText.textContent = slider.value;
    sliderValueText.classList.add("editor-width-slider-value");
    sliderValueText.id = "editor-width-slider-value";
    sliderValueText.addEventListener("click", () => {
      if (this.noteWidthLocked) {
        this.showLockedNotice();
        return;
      }
      this.resetEditorWidth();
    });
    this.registerDomEvent(sliderValueText, "contextmenu", (event) => {
      event.preventDefault();
      this.showWidthContextMenu(event);
    });
    const sliderContainer = document.createElement("span");
    sliderContainer.classList.add("editor-width-slider-container");
    sliderContainer.appendChild(slider);
    this.registerDomEvent(sliderContainer, "pointerdown", () => {
      if (this.noteWidthLocked) {
        this.showLockedNotice();
      }
    });
    const statusBarItemEl = this.addStatusBarItem();
    statusBarItemEl.appendChild(sliderContainer);
    statusBarItemEl.appendChild(sliderValueText);
  }
  showLockedNotice() {
    new import_obsidian3.Notice("当前笔记宽度已锁定，请右键状态栏锁形图标并选择“恢复全局宽度”");
  }
  setSliderLocked(locked, width) {
    this.noteWidthLocked = locked;
    const slider = document.getElementById("editor-width-slider");
    const sliderValue = document.getElementById("editor-width-slider-value");
    if (slider) {
      slider.disabled = locked;
      slider.setAttribute("aria-disabled", locked ? "true" : "false");
      if (width !== void 0) {
        slider.value = width.toString();
      }
    }
    if (sliderValue) {
      sliderValue.empty();
      if (locked) {
        import_obsidian3.setIcon(sliderValue, "lock");
        sliderValue.setAttribute("aria-label", "当前笔记宽度已锁定，右键可恢复全局宽度");
      } else {
        sliderValue.textContent = (width !== void 0 ? width : this.settings.sliderPercentage).toString();
        sliderValue.setAttribute("aria-label", "编辑器宽度");
      }
    }
  }
  showWidthContextMenu(event) {
    const menu = new import_obsidian3.Menu();
    menu.addItem((item) => {
      item.setTitle("保存为当前笔记宽度").setIcon("save").onClick(async () => {
        await this.saveWidthToCurrentNote();
      });
    });
    menu.addItem((item) => {
      item.setTitle("恢复全局宽度").setIcon("rotate-ccw").onClick(async () => {
        await this.restoreGlobalWidth();
      });
    });
    menu.showAtMouseEvent(event);
  }
  async saveWidthToCurrentNote() {
    const file = this.app.workspace.getActiveFile();
    if (!file || file.extension !== "md") {
      new import_obsidian3.Notice("请先打开一篇 Markdown 笔记");
      return;
    }
    const slider = document.getElementById("editor-width-slider");
    const width = slider ? slider.value : this.settings.sliderPercentage;
    if (!this.validateString(width)) {
      new WarningModal(this.app).open();
      return;
    }
    try {
      await this.app.fileManager.processFrontMatter(file, (frontmatter) => {
        frontmatter["editor-width"] = Number(width);
      });
      // 当前值保存到笔记后，全局值恢复为插件设置的默认百分比。
      // 当前笔记继续通过视图级 CSS 变量使用保存时的宽度。
      this.settings.sliderPercentage = this.settings.sliderPercentageDefault;
      await this.saveSettings();
      this.updateEditorStyle();
      this.updateEditorStyleYAMLHelper(width);
      this.setSliderLocked(true, width);
      new import_obsidian3.Notice(`已将当前笔记宽度保存为 ${width}`);
    } catch (error) {
      console.error("Failed to save editor-width frontmatter:", error);
      new import_obsidian3.Notice("保存当前笔记宽度失败");
    }
  }
  async restoreGlobalWidth() {
    const file = this.app.workspace.getActiveFile();
    if (!file || file.extension !== "md") {
      new import_obsidian3.Notice("请先打开一篇 Markdown 笔记");
      return;
    }
    try {
      await this.app.fileManager.processFrontMatter(file, (frontmatter) => {
        delete frontmatter["editor-width"];
      });
      this.clearActiveEditorWidthOverride();
      this.resetEditorWidth();
      // 元数据缓存可能尚未完成刷新，直接应用全局默认样式，避免旧值残留。
      this.updateEditorStyle();
      this.clearActiveEditorWidthOverride();
      this.setSliderLocked(false, this.settings.sliderPercentageDefault);
      new import_obsidian3.Notice("已移除当前笔记宽度，并恢复全局默认宽度");
    } catch (error) {
      console.error("Failed to remove editor-width frontmatter:", error);
      new import_obsidian3.Notice("恢复全局宽度失败");
    }
  }
  // ---------------------------- SLIDER -------------------------------------
  cleanUpResources() {
    this.resetEditorWidth();
  }
  resetEditorWidth() {
    this.settings.sliderPercentage = this.settings.sliderPercentageDefault;
    const styleElements = document.getElementsByClassName("editor-width-slider");
    const slider = document.getElementById("editor-width-slider");
    const sliderValue = document.getElementById("editor-width-slider-value");
    if (slider) {
      if (sliderValue) {
        slider.value = this.settings.sliderPercentageDefault;
        sliderValue.textContent = this.settings.sliderPercentageDefault.toString();
      }
    }
    this.saveSettings();
    this.updateEditorStyleYAML();
  }
  // add element that contains all of the styling elements we need
  addStyle() {
    const css = document.createElement("style");
    css.id = "additional-editor-css";
    document.getElementsByTagName("head")[0].appendChild(css);
    document.body.classList.add("additional-editor-css");
  }
  // update the styles (at the start, or as the result of a settings change)
  updateEditorStyle() {
    const styleElement = document.getElementById("additional-editor-css");
    if (!styleElement)
      throw "additional-editor-css element not found!";
    else {
      styleElement.innerText = `
			body {
			  	--file-line-width: calc(700px + 10 * ${this.settings.sliderPercentage}px) !important;
			}
		`;
    }
  }
  // update the styles (at the start, or as the result of a settings change)
  updateEditorStyleYAMLHelper(editorWidth) {
    const leaf = this.app.workspace.activeLeaf;
    if (leaf && leaf.view && leaf.view.containerEl) {
      leaf.view.containerEl.style.setProperty(
        "--file-line-width",
        `calc(700px + 10 * ${editorWidth}px)`,
        "important"
      );
    }
  }
  clearActiveEditorWidthOverride() {
    const leaf = this.app.workspace.activeLeaf;
    if (leaf && leaf.view && leaf.view.containerEl) {
      leaf.view.containerEl.style.removeProperty("--file-line-width");
    }
  }
  validateString(inputString) {
    return this.pattern.test(inputString);
  }
  updateEditorStyleYAML() {
    // 全局宽度始终写在 body，当前笔记的 editor-width 只覆盖当前视图。
    this.updateEditorStyle();
    this.clearActiveEditorWidthOverride();
    const file = this.app.workspace.getActiveFile();
    if (file && file.name) {
      const metadata = this.app.metadataCache.getFileCache(file);
      const frontmatter = metadata && metadata.frontmatter;
      if (frontmatter && Object.prototype.hasOwnProperty.call(frontmatter, "editor-width")) {
        const editorWidth = frontmatter["editor-width"];
        if (this.validateString(editorWidth)) {
          this.updateEditorStyleYAMLHelper(editorWidth);
          this.setSliderLocked(true, editorWidth);
          return;
        }
        this.setSliderLocked(false, this.settings.sliderPercentage);
        new WarningModal(this.app).open();
        return;
      }
    }
    this.setSliderLocked(false, this.settings.sliderPercentage);
  }
  // update the styles (at the start, or as the result of a settings change)
  updateSliderStyle() {
    const styleElements = document.getElementsByClassName("editor-width-slider");
    if (styleElements.length === 0) {
      throw new Error("editor-width-slider-value element not found!");
    } else {
      const styleElement = styleElements[0];
      styleElement.style.width = this.settings.sliderWidth + "px";
    }
  }
  // Method to load settings
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  // Method to store settings
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
